name: StockedUp
version: 0.0.0
author: EquaFerrous
main: me.equaferrous.stockedup.Main
api-version: 1.19
description: Provides the functionality for the StockedUp! minigame.
permissions:
  gameAdmin:
    description: Gives access to commands to assist with running the game.
    default: op