name: McMinigame
version: 0.0.0
author: EquaFerrous
main: me.equaferrous.mcminigame.Main
api-version: 1.19
description: Provides the functionality for the shop coop minigame.
permissions:
  gameAdmin:
    description: Gives access to commands to assist with running the game.
    default: op